/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaMVCViews;
import JavaMVCControllers.*;
import JavaMVCModels.*;
import java.util.Date;



/**
 *
 * @author gigik_user
 */
public class MasterPage extends javax.swing.JFrame {
    
    private AgendaController ctrlAgenda = new AgendaController();
    private LembreteController ctrlLembrete = new LembreteController();
    private Agenda agendinha;
    private Lembrete lembrete;
    private Lembrete lembrete_modificado;
    private Lembrete lembrete_excluir;
    /**
     * Creates new form NewJFrame
     */
    public MasterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_padrao = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        home = new javax.swing.JPanel();
        quero_criar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crie_Agenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeAgendaForm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeDonoForm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipoForm = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();
        menu = new javax.swing.JTabbedPane();
        veja_agenda = new javax.swing.JPanel();
        textoAgendinha = new javax.swing.JLabel();
        modifique_agenda = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        novoDonoModificado = new javax.swing.JTextField();
        novoTipoModificado = new javax.swing.JTextField();
        novaAgendaModificada = new javax.swing.JTextField();
        confirmModifyAgenda = new javax.swing.JButton();
        adicione_lembrete = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        confirmAddLembrete = new javax.swing.JButton();
        modifique_lembrete = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nova_descricao = new javax.swing.JTextArea();
        editar_lembrete = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        buscar_palavra = new javax.swing.JTextField();
        modificar_busca_lembrete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        resultado_modifique_lembrete = new javax.swing.JLabel();
        veja_lembrete = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricao_search = new javax.swing.JTextArea();
        search_lembrete = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lembrete_encontrado = new javax.swing.JEditorPane();
        exclua_lembretes = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        excluir_todos = new javax.swing.JButton();
        excluir_lembrete = new javax.swing.JButton();
        excluir_resultado_lembrete = new javax.swing.JLabel();
        excluir_buscar_descricao = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        excluir_buscar_lembrete = new javax.swing.JButton();

        dialog_padrao.setResizable(false);
        dialog_padrao.setSize(new java.awt.Dimension(300, 200));

        jLabel19.setText("Sucesso!");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_padraoLayout = new javax.swing.GroupLayout(dialog_padrao.getContentPane());
        dialog_padrao.getContentPane().setLayout(dialog_padraoLayout);
        dialog_padraoLayout.setHorizontalGroup(
            dialog_padraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_padraoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(dialog_padraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(dialog_padraoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );
        dialog_padraoLayout.setVerticalGroup(
            dialog_padraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_padraoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19)
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quero_criar.setText("Quero criar!");
        quero_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quero_criarActionPerformed(evt);
            }
        });

        jLabel8.setText("Crie sua primeira agenda para explorar suas funcionalidades.");

        jLabel7.setText("Seu agrupador de agendas e lembretes!");

        jLabel5.setText("Benvindo ao NotMemmento!");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel8))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel5))))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(quero_criar)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(52, 52, 52)
                .addComponent(quero_criar)
                .addGap(84, 84, 84))
        );

        crie_Agenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Agenda"));
        crie_Agenda.setVisible(false);

        jLabel1.setText("Nome da Agenda:");

        nomeAgendaForm.setText("Digite um nome");
        nomeAgendaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAgendaFormActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do dono:");

        nomeDonoForm.setText("Digite um nome");

        jLabel3.setText("Tipo:");

        tipoForm.setText("Digite um tipo");
        tipoForm.setToolTipText("");

        confirma.setText("Confirma");
        confirma.setToolTipText("");
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crie_AgendaLayout = new javax.swing.GroupLayout(crie_Agenda);
        crie_Agenda.setLayout(crie_AgendaLayout);
        crie_AgendaLayout.setHorizontalGroup(
            crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crie_AgendaLayout.createSequentialGroup()
                .addGroup(crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crie_AgendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(tipoForm)
                            .addComponent(nomeDonoForm, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(nomeAgendaForm)))
                    .addGroup(crie_AgendaLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(confirma)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        crie_AgendaLayout.setVerticalGroup(
            crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crie_AgendaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeAgendaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nomeDonoForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(confirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        veja_agenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Você está vendo sua Agenda"));
        veja_agenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                veja_agendaFocusGained(evt);
            }
        });

        textoAgendinha.setText("jLabel12");

        javax.swing.GroupLayout veja_agendaLayout = new javax.swing.GroupLayout(veja_agenda);
        veja_agenda.setLayout(veja_agendaLayout);
        veja_agendaLayout.setHorizontalGroup(
            veja_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veja_agendaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(textoAgendinha)
                .addContainerGap(562, Short.MAX_VALUE))
        );
        veja_agendaLayout.setVerticalGroup(
            veja_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veja_agendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoAgendinha)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        menu.addTab("Veja sua Agenda", veja_agenda);

        modifique_agenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Você está modificando sua Agenda"));

        jLabel9.setText("Novo nome da Agenda:");

        jLabel10.setText("Novo nome do Dono:");

        jLabel11.setText("Novo tipo:");

        novoDonoModificado.setText("novo dono");

        novoTipoModificado.setText("novo tipo");

        novaAgendaModificada.setText("nova agenda");

        confirmModifyAgenda.setText("Confirmar");
        confirmModifyAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmModifyAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifique_agendaLayout = new javax.swing.GroupLayout(modifique_agenda);
        modifique_agenda.setLayout(modifique_agendaLayout);
        modifique_agendaLayout.setHorizontalGroup(
            modifique_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifique_agendaLayout.createSequentialGroup()
                .addGroup(modifique_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifique_agendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(modifique_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(modifique_agendaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(modifique_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(novoTipoModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(novaAgendaModificada, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(novoDonoModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(modifique_agendaLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(confirmModifyAgenda)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        modifique_agendaLayout.setVerticalGroup(
            modifique_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifique_agendaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novaAgendaModificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoDonoModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoTipoModificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(confirmModifyAgenda)
                .addGap(28, 28, 28))
        );

        menu.addTab("Modifique sua Agenda", modifique_agenda);

        adicione_lembrete.setBorder(javax.swing.BorderFactory.createTitledBorder("Você está adicionando um Lembrete"));

        jLabel4.setText("Escreva o Lembrete:");

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        jLabel6.setText("ATENÇÂO: O lembrete terá a data e hora de criação gravadas nele.");

        confirmAddLembrete.setText("Confirmar");
        confirmAddLembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddLembreteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adicione_lembreteLayout = new javax.swing.GroupLayout(adicione_lembrete);
        adicione_lembrete.setLayout(adicione_lembreteLayout);
        adicione_lembreteLayout.setHorizontalGroup(
            adicione_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicione_lembreteLayout.createSequentialGroup()
                .addGroup(adicione_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adicione_lembreteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(adicione_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(adicione_lembreteLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(confirmAddLembrete)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        adicione_lembreteLayout.setVerticalGroup(
            adicione_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicione_lembreteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(confirmAddLembrete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.addTab("Adicione Lembrete", adicione_lembrete);

        modifique_lembrete.setBorder(javax.swing.BorderFactory.createTitledBorder("Você está modificando um Lembrete"));

        jLabel14.setText("Nova Descrição: ");

        nova_descricao.setColumns(20);
        nova_descricao.setRows(5);
        jScrollPane3.setViewportView(nova_descricao);

        editar_lembrete.setText("Confirmar");
        editar_lembrete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editar_lembreteMouseClicked(evt);
            }
        });

        jLabel15.setText("Digite a descrição a ser buscada: ");

        buscar_palavra.setText("Descrição");

        modificar_busca_lembrete.setText("Buscar");
        modificar_busca_lembrete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificar_busca_lembreteMouseClicked(evt);
            }
        });

        jLabel16.setText("Este será o lembrete modificado:");

        resultado_modifique_lembrete.setText("jLabel17");
        resultado_modifique_lembrete.setVisible(false);

        javax.swing.GroupLayout modifique_lembreteLayout = new javax.swing.GroupLayout(modifique_lembrete);
        modifique_lembrete.setLayout(modifique_lembreteLayout);
        modifique_lembreteLayout.setHorizontalGroup(
            modifique_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifique_lembreteLayout.createSequentialGroup()
                .addGroup(modifique_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifique_lembreteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(modifique_lembreteLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(editar_lembrete))
                    .addGroup(modifique_lembreteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modifique_lembreteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(modificar_busca_lembrete))
                    .addGroup(modifique_lembreteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(modifique_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buscar_palavra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(modifique_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(resultado_modifique_lembrete))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        modifique_lembreteLayout.setVerticalGroup(
            modifique_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifique_lembreteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifique_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modifique_lembreteLayout.createSequentialGroup()
                        .addGroup(modifique_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar_palavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultado_modifique_lembrete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modificar_busca_lembrete)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editar_lembrete)
                .addContainerGap())
        );

        menu.addTab("Modifique um Lembrete", modifique_lembrete);

        veja_lembrete.setBorder(javax.swing.BorderFactory.createTitledBorder("Você está procurando através de uma descrição"));

        jLabel12.setText("Digite a descrição a ser buscada:");

        descricao_search.setColumns(20);
        descricao_search.setRows(5);
        jScrollPane2.setViewportView(descricao_search);

        search_lembrete.setText("Buscar");
        search_lembrete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_lembreteMouseClicked(evt);
            }
        });

        jLabel13.setText("Lembrete: ");

        lembrete_encontrado.setVisible(false);
        jScrollPane5.setViewportView(lembrete_encontrado);

        javax.swing.GroupLayout veja_lembreteLayout = new javax.swing.GroupLayout(veja_lembrete);
        veja_lembrete.setLayout(veja_lembreteLayout);
        veja_lembreteLayout.setHorizontalGroup(
            veja_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veja_lembreteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(veja_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(veja_lembreteLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(veja_lembreteLayout.createSequentialGroup()
                        .addGroup(veja_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(veja_lembreteLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(search_lembrete))
                            .addGroup(veja_lembreteLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel13)))
                        .addContainerGap(249, Short.MAX_VALUE))))
        );
        veja_lembreteLayout.setVerticalGroup(
            veja_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veja_lembreteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(veja_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(veja_lembreteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(search_lembrete)
                .addGap(37, 37, 37))
        );

        menu.addTab("Veja um Lembrete", veja_lembrete);

        exclua_lembretes.setBorder(javax.swing.BorderFactory.createTitledBorder("Você está excluindo Lembrete"));

        jLabel17.setText("Exclua Todos");

        jLabel18.setText("Exclua o lembrete:");

        excluir_todos.setText("Confirmar");
        excluir_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_todosActionPerformed(evt);
            }
        });

        excluir_lembrete.setText("Excluir");
        excluir_lembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_lembreteActionPerformed(evt);
            }
        });

        excluir_resultado_lembrete.setText("jLabel19");
        excluir_resultado_lembrete.setVisible(false);

        excluir_buscar_descricao.setText("Descrição");

        jLabel20.setText("Digite a descrição a ser buscada:");

        excluir_buscar_lembrete.setText("Buscar");
        excluir_buscar_lembrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_buscar_lembreteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exclua_lembretesLayout = new javax.swing.GroupLayout(exclua_lembretes);
        exclua_lembretes.setLayout(exclua_lembretesLayout);
        exclua_lembretesLayout.setHorizontalGroup(
            exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exclua_lembretesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(excluir_buscar_lembrete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excluir_lembrete)
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exclua_lembretesLayout.createSequentialGroup()
                .addGroup(exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exclua_lembretesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17))
                    .addGroup(exclua_lembretesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluir_todos)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(excluir_buscar_descricao))))
                .addGap(163, 163, 163)
                .addGroup(exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(excluir_resultado_lembrete))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        exclua_lembretesLayout.setVerticalGroup(
            exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exclua_lembretesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(excluir_todos)
                .addGap(29, 29, 29)
                .addGroup(exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluir_resultado_lembrete)
                    .addComponent(excluir_buscar_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(exclua_lembretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluir_lembrete)
                    .addComponent(excluir_buscar_lembrete))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        menu.addTab("Exclua Lembretes", exclua_lembretes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(crie_Agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(crie_Agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 352, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        // TODO add your handling code here:
        String nomeAgenda = nomeAgendaForm.getText();
        String nomeDono = nomeDonoForm.getText();
        String tipo = tipoForm.getText();
        agendinha = ctrlAgenda.createAgenda(nomeAgenda, nomeDono, tipo);
        crie_Agenda.setVisible(false);
        
        System.out.println(ctrlAgenda.readAgenda(agendinha));
    }//GEN-LAST:event_confirmaActionPerformed

    private void nomeAgendaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAgendaFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAgendaFormActionPerformed

    private void quero_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quero_criarActionPerformed
        // TODO add your handling code here:
        crie_Agenda.setVisible(true);
        home.setVisible(false);        
    }//GEN-LAST:event_quero_criarActionPerformed

    private void search_lembreteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_lembreteMouseClicked
        // TODO add your handling code here:
        lembrete = ctrlAgenda.buscaDeLembrete(agendinha, descricao_search.getText());
        lembrete_encontrado.setContentType("text/html");
        lembrete_encontrado.setText(ctrlLembrete.readLembrete(lembrete));
        lembrete_encontrado.setVisible(true);        
    }//GEN-LAST:event_search_lembreteMouseClicked

    private void confirmModifyAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmModifyAgendaActionPerformed
        // TODO add your handling code here:
        ctrlAgenda.updateAgenda(agendinha, novaAgendaModificada.getText(), novoDonoModificado.getText(), novoTipoModificado.getText());
        novaAgendaModificada.setText("");
        novoDonoModificado.setText(""); 
        novoTipoModificado.setText("");        
        dialog_padrao.setVisible(true);
    }//GEN-LAST:event_confirmModifyAgendaActionPerformed

    private void veja_agendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_veja_agendaFocusGained
        // TODO add your handling code here:
        String textAgenda = ctrlAgenda.readAgenda(agendinha);
        textoAgendinha.setText(textAgenda);
        textoAgendinha.setVisible(true);
    }//GEN-LAST:event_veja_agendaFocusGained

    private void confirmAddLembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddLembreteActionPerformed
        // TODO add your handling code here:
        ctrlAgenda.adicionaLembrete(agendinha, new Date(), descricao.getText());
        descricao.setText("");
        
        
        dialog_padrao.setVisible(true);
    }//GEN-LAST:event_confirmAddLembreteActionPerformed

    private void editar_lembreteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_lembreteMouseClicked
        // TODO add your handling code here:
        ctrlLembrete.updateLembrete(lembrete_modificado, new Date(),nova_descricao.getText());
        nova_descricao.setText("");
        dialog_padrao.setVisible(true);
    }//GEN-LAST:event_editar_lembreteMouseClicked

    private void modificar_busca_lembreteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_busca_lembreteMouseClicked
        // TODO add your handling code here:
        lembrete_modificado = ctrlAgenda.buscaDeLembrete(agendinha, buscar_palavra.getText());
        resultado_modifique_lembrete.setText(ctrlLembrete.readLembrete(lembrete_modificado));
        resultado_modifique_lembrete.setVisible(true);        
    }//GEN-LAST:event_modificar_busca_lembreteMouseClicked

    private void excluir_buscar_lembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_buscar_lembreteActionPerformed
        // TODO add your handling code here:
        lembrete_excluir = ctrlAgenda.buscaDeLembrete(agendinha, excluir_buscar_descricao.getText());
        excluir_resultado_lembrete.setText(ctrlLembrete.readLembrete(lembrete_excluir));
        excluir_resultado_lembrete.setVisible(true);                
    }//GEN-LAST:event_excluir_buscar_lembreteActionPerformed

    private void excluir_lembreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_lembreteActionPerformed
        // TODO add your handling code here:
        ctrlAgenda.deleteLembrete(agendinha, lembrete_excluir);
        dialog_padrao.setVisible(true);
    }//GEN-LAST:event_excluir_lembreteActionPerformed

    private void excluir_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_todosActionPerformed
        // TODO add your handling code here:
        ctrlAgenda.deleteAllLembretes(agendinha);
        dialog_padrao.setVisible(true);

    }//GEN-LAST:event_excluir_todosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dialog_padrao.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterPage().setVisible(true);
            }            
        });
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adicione_lembrete;
    private javax.swing.JTextField buscar_palavra;
    private javax.swing.JButton confirmAddLembrete;
    private javax.swing.JButton confirmModifyAgenda;
    private javax.swing.JButton confirma;
    private javax.swing.JPanel crie_Agenda;
    private javax.swing.JTextArea descricao;
    private javax.swing.JTextArea descricao_search;
    private javax.swing.JDialog dialog_padrao;
    private javax.swing.JButton editar_lembrete;
    private javax.swing.JPanel exclua_lembretes;
    private javax.swing.JTextField excluir_buscar_descricao;
    private javax.swing.JButton excluir_buscar_lembrete;
    private javax.swing.JButton excluir_lembrete;
    private javax.swing.JLabel excluir_resultado_lembrete;
    private javax.swing.JButton excluir_todos;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JEditorPane lembrete_encontrado;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JButton modificar_busca_lembrete;
    private javax.swing.JPanel modifique_agenda;
    private javax.swing.JPanel modifique_lembrete;
    private javax.swing.JTextField nomeAgendaForm;
    private javax.swing.JTextField nomeDonoForm;
    private javax.swing.JTextField novaAgendaModificada;
    private javax.swing.JTextArea nova_descricao;
    private javax.swing.JTextField novoDonoModificado;
    private javax.swing.JTextField novoTipoModificado;
    private javax.swing.JButton quero_criar;
    private javax.swing.JLabel resultado_modifique_lembrete;
    private javax.swing.JButton search_lembrete;
    private javax.swing.JLabel textoAgendinha;
    private javax.swing.JTextField tipoForm;
    private javax.swing.JPanel veja_agenda;
    private javax.swing.JPanel veja_lembrete;
    // End of variables declaration//GEN-END:variables

}
