/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaMVCViews;
import JavaMVCControllers.*;
import JavaMVCModels.*;



/**
 *
 * @author gigik_user
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private ControllerStringToModel controller = new ControllerStringToModel();
    private AgendaController ctrlAgenda = new AgendaController();
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmaAgenda = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        quero_criar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Crie_Agenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeAgendaForm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeDonoForm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipoForm = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();

        confirmaAgenda.setTitle("AgendaConfirmada");
        confirmaAgenda.setAlwaysOnTop(true);

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout confirmaAgendaLayout = new javax.swing.GroupLayout(confirmaAgenda.getContentPane());
        confirmaAgenda.getContentPane().setLayout(confirmaAgendaLayout);
        confirmaAgendaLayout.setHorizontalGroup(
            confirmaAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaAgendaLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel4)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        confirmaAgendaLayout.setVerticalGroup(
            confirmaAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmaAgendaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        confirmaAgenda.getAccessibleContext().setAccessibleParent(confirma);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quero_criar.setText("Quero criar!");
        quero_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quero_criarActionPerformed(evt);
            }
        });

        jLabel8.setText("Crie sua primeira agenda para explorar suas funcionalidades.");

        jLabel7.setText("Seu agrupador de agendas e lembretes!");

        jLabel5.setText("Benvindo ao NotMemmento!");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(quero_criar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(73, 73, 73))))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(quero_criar)
                .addGap(59, 59, 59))
        );

        Crie_Agenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Agenda"));
        Crie_Agenda.setVisible(false);

        jLabel1.setText("Nome da Agenda:");

        nomeAgendaForm.setText("Digite um nome");
        nomeAgendaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAgendaFormActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do dono:");

        nomeDonoForm.setText("Digite um nome");

        jLabel3.setText("Tipo:");

        tipoForm.setText("Digite um tipo");
        tipoForm.setToolTipText("");

        confirma.setText("Confirma");
        confirma.setToolTipText("");
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Crie_AgendaLayout = new javax.swing.GroupLayout(Crie_Agenda);
        Crie_Agenda.setLayout(Crie_AgendaLayout);
        Crie_AgendaLayout.setHorizontalGroup(
            Crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crie_AgendaLayout.createSequentialGroup()
                .addGroup(Crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Crie_AgendaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(Crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(tipoForm)
                                .addComponent(nomeDonoForm, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)))
                        .addGroup(Crie_AgendaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(Crie_AgendaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nomeAgendaForm)))
                    .addGroup(Crie_AgendaLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(confirma)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        Crie_AgendaLayout.setVerticalGroup(
            Crie_AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crie_AgendaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nomeAgendaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nomeDonoForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(confirma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Crie_Agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Crie_Agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        // TODO add your handling code here:
        String nomeAgenda = nomeAgendaForm.getText();
        String nomeDono = nomeDonoForm.getText();
        String tipo = tipoForm.getText();
        Agenda agendinha = controller.includesAgenda(nomeAgenda, nomeDono, tipo);
        Crie_Agenda.setVisible(false);
        
        System.out.println(ctrlAgenda.readAgenda(agendinha));
    }//GEN-LAST:event_confirmaActionPerformed

    private void nomeAgendaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAgendaFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAgendaFormActionPerformed

    private void quero_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quero_criarActionPerformed
        // TODO add your handling code here:
        Crie_Agenda.setVisible(true);
        Home.setVisible(false);
        
    }//GEN-LAST:event_quero_criarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Crie_Agenda;
    private javax.swing.JPanel Home;
    private javax.swing.JButton confirma;
    private javax.swing.JDialog confirmaAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomeAgendaForm;
    private javax.swing.JTextField nomeDonoForm;
    private javax.swing.JButton quero_criar;
    private javax.swing.JTextField tipoForm;
    // End of variables declaration//GEN-END:variables

}
